### ISSUE TITLE
Firefox extension may not be needed

### ISSUE THREAD

**Issue by sstawecki** [opentok/accelerator-screen-sharing-js#21]
### General information

- Library version(s): 1.0.27
- iOS/Android/Browser version(s): Firefox Desktop
- Devices/Simulators/Machine affected: Firefox v52+

#### Expected behavior
Be able to share screen in Firefox 52+ without any extension based on this reference:
https://tokbox.com/developer/guides/screen-sharing/js/
"As of Firefox 52, an extension (or whitelist listing) is no longer needed for screen sharing. Firefox prompts the end user for access to a screen, window, or application, as it would for access to the camera. For more information, see this Mozilla blog post. To support screen sharing in older versions of Firefox, see the OpenTok screensharing-extensions repo on GitHub."

#### Actual behavior
Accelerator core asks for install the screen sharing extension.

#### Steps to reproduce
Share screen in Firefox using the latest version (or any version 52+)

## Question or Feature Request
Be able to share screen on Firefox 52+ without any screen sharing extension.

**Comment by maikthomas** [comment]
@sstawecki 
Thanks for bringing this to our attention.
We should have a fix for this soon, I'll update you here when we do 👍 
Cheers,
Mike

**Comment by maikthomas** [comment]
@sstawecki,
This has been fixed, please upgrade to 1.0.29.
Thanks,
Mike
