### ISSUE TITLE
How do I integrate this code into opentok / opentok-rtc

### ISSUE THREAD

**Issue by minto-b** [opentok/accelerator-screen-sharing-js#33]
Hi, I do not have any engineering background but I was able to download and make some edits to opentok / opentok-rtc, to be specific to translate the site into Japanese, make some changes in the logo and upload it to my own server. However, I have been struggling to integrate accelerator-screen-sharing-js into the web application. I have read through a lot of blogs, articles, and tutorials but none seemed to really click to me. 

So here is my question. 

How do I add screen sharing into opentok / opentok-rtc open source code? 

If anybody could suggest me a blog, article, or tutorial that would be much appreciated. 

Anyways, I am very thankful for the team at opentok to make this available and giving me the chance to immerse myself in into the world of software engineering.

Best, 

Minto 

## New issue checklist

- [ ] I have read all of the [`README`](/README.md) 
- [ ] I have searched [existing issues](https://github.com/opentok/accelerator-screen-sharing-js/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by MichaelJolley** [comment]
Hi @minto-b, sorry for the delay in responding. This library isn't compatible with opentok-rtc. That repo already includes the capability to do screen sharing. In that repo, you can find out how to enable it at https://github.com/opentok/opentok-rtc#screen-sharing-configuration.
